# Generated by Django 4.2.6 on 2023-10-31 01:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emprendedor_id', models.UUIDField()),
                ('cedula', models.PositiveIntegerField()),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=16)),
                ('address', models.CharField(default='', max_length=264)),
                ('articles', models.ManyToManyField(to='providers.article')),
            ],
        ),
    ]
