# Generated by Django 4.2.6 on 2023-11-01 07:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_article_name_alter_provider_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='emprendedor_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
